### PR TITLE
Run function to get index

### PR DESCRIPTION
**Pull request by siscia**
Hi,

I add a little functionality to your sorted_set.

Now it is possible to run a function on the input values, the output of the function will be used as index inside the tree, while the value itself will be stored.

I also make a little change to the inspect function, now it prints the values and not the keys.

If you have any question please let me know :)

Cheers

### CODE REVIEW

**Comment by tyre** [comment]
Hey @siscia, thanks for the PR!

Could you explain the use case for this?

I'm not sure what the desired functionality is in a few cases and it introduces some strange results. Since this affects pretty much every function, we'd want to have test-cases describing how it works.

For example, adding a member and then checking if it is a member returns false:

``` elixir
SortedSet.new(fn {a, _b} -> a end, [])
  |> SortedSet.put({50, 40})
  |> SortedSet.member?({50, 40})
# false
```

Adding a different member overwrites the old one, which it should given the selector, but this

``` elixir
SortedSet.new(fn {a, _b} -> a end, [])
  |> SortedSet.put({50, 40})
  |> SortedSet.put({50, 30})
  |> SortedSet.to_list
# [{50, 30}]
```

The set behaviour is now undefined for many functions (even through the string representation of the sets is exactly the same):

``` elixir
set_a = SortedSet.new([50])
# #SortedSet<'2'>
set_b = SortedSet.new(fn {a, _b} -> a end, [{50, 40}])
# #SortedSet<'2'>
SortedSet.union(set_a, set_b)
# ** (FunctionClauseError) no function clause matching in :erl_eval."-inside-an-interpreted-fun-"/1
SortedSet.union(set_b, set_a)
# #SortedSet<[50, {50, 40}]>
```

Or it is order dependent:

``` elixir
set_a = SortedSet.new([{50, 40}])
set_b = SortedSet.new(fn {a, _b} -> a end, [{50, 40}])
# #SortedSet<[{50, 40}]>
SortedSet.union(set_a, set_b)
# #SortedSet<'2'>
SortedSet.union(set_b, set_a)
# #SortedSet<[{50, 40}]>
```

**Comment by siscia** [comment]
Hi @tyre,

#### Use cases

When we use a sorted set normally we want to decide what logic follow to order the set itself.

Maybe you want to keep in memory all the order made in a e-commerce by total amount spend, or you need keep some tuple in order by receive time, or you want to keep the order by priority.

#### Membership

sorry about the membership check, I was a little tired yesterday... It should be fixed now.

#### Overwrite

``` elixir
SortedSet.new(fn {a, _b} -> a end, [])
  |> SortedSet.put({50, 40})
  |> SortedSet.put({50, 30})
  |> SortedSet.to_list
# [{50, 30}]
```

It seems to work fine, the old member is overwrited by the new one, am I missing something ?

#### Elixir binary

``` elixir
set_a = SortedSet.new([50])
# #SortedSet<'2'>
set_b = SortedSet.new(fn {a, _b} -> a end, [{50, 40}])
# #SortedSet<'2'>
```

Here I find the behaviour of elixir a little lacking, however is simply a problem in the specific case you have quoted.

``` elixir
c = SortedSet.new([50])             
#SortedSet<'2'>
c = SortedSet.put(c, 2)  
#SortedSet<[2, 50]>
c = SortedSet.put(c, '2')
#SortedSet<[2, 50, '2']>
```

### Union

The problem with union is due to the fact that we grow the smaller (or the second) set.

In your example the set_b have a specific selector, and it will crash when trying to execute
`(fn {a, _b} -> a end).[50]`

A very good type system would not allow this problem to happen, but in our case we need work around it. 

Actually I don't see many use case where merge two different sorted set makes much sense so in my opinion is still debatable if we want to add this complexity, however I can see few alternatives.
1. Provide an `union/3` which will take two set and a selector, and will build a complete new set using the new selector. A little wasteful but it will work.
2. Another option is to keep `union/2` and always grow the first or the second or the bigger set.
   
   To always grow the bigger set is a little unwise in my opinion, since the dimension is not know a "code-writing" time.
   The other two option can be a little wasteful.
3. Also we could provide an `union/3` that will take as input the two set to merge and another set to use as base for the merge so that the programmer can decide what is best in each case.
4. Finally we could simply drop the features that I keep seeing debatable.

Here it really depends on how much freedom we want the developer to have, in order from the most free to the less free options: 3, 2, 1, 4

#### to_list and inspect

I changed a little bit here, trying to keep your original implementation, however a few thoughts.

In my opinion to_list should return a list of the values while inspect should show the values and the index sorted by index.

Let me know what you think about everything.

Notable implementation of SortedSet are the one of Java: http://docs.oracle.com/javase/8/docs/api/java/util/SortedSet.html
The one from Microsoft: https://msdn.microsoft.com/en-us/library/dd412070%28v=vs.110%29.aspx
And the one in Clojure: http://clojuredocs.org/clojure.core/sorted-set-by

**Comment by tyre** [comment]
Thank you for linking to the other implementations, that was really helpful.

It sounds like we have two things: the underlying comparator and a function for uniqueness (which determines the key for the RedBlackTree or whatever underlying implementation.) This means that [RedBlackTree](https://github.com/senecasystems/redblacktree) would need to be refactored to take a comparator function or default to elixir/erlang term comparison. I'm happy to make that change.

So for your hypothetical example:

``` elixir
def compare(left, right) do
  cond do
    left < right -> -1
    left === right -> 0
    left > right -> 1
  end
end

def compare_orders(%{id: id1, revenue: revenue1}, %{id: id2, revenue: revenue2}) do
  case compare(revenue1, revenue2) do
    # In the case that the revenues are the same, fall back to id ordering
    0 -> compare(id1, id2)
    revenue_comparison -> revenue_comparison
  end
end

revenues_by_order_id = SortedSet.new(
  [],
  comparator: &compare_orders/2,
  unique_by: fn (%{id: id}) -> id end
)

revenues_by_order_id = SortedSet.put(revenues_by_order_id, %{id: 1, revenue: 50})
|> SortedSet.put(revenues_by_order_id, %{id: 2, revenue: 30})
# #SortedSet<[%{id: 2, revenue: 30}, %{id: 1, revenue: 50}]>

# Someone changes their order
revenues_by_order_id = SortedSet.put(revenues_by_order_id, %{id: 1, revenue: 20})
# #SortedSet<[%{id: 1, revenue: 20}, %{id: 2, revenue: 30}]>

# A new order with the same revenue is posted
revenues_by_order_id = SortedSet.put(revenues_by_order_id, %{id: 4, revenue: 20})
# #SortedSet<[%{id: 1, revenue: 20}, %{id: 4, revenue: 20}, %{id: 2, revenue: 30}]>

# And again, to show fallback sorting
revenues_by_order_id = SortedSet.put(revenues_by_order_id, %{id: 3, revenue: 20})
# #SortedSet<[%{id: 1, revenue: 20}, %{id: 3, revenue: 20}, %{id: 4, revenue: 20}, %{id: 2, revenue: 30}]>
```

We still have uniqueness by id and sorting according to what we want to compare. Note that, in order to maintain the properties of a set, if the comparison operator returns `0` then we have to replace the current item, regardless of what the `unique_by` operator says.

Another option is to fall back to compare the `unique_by` results to break ties. In which case the following would be the same as the above cases:

``` elixir
revenues_by_order_id = SortedSet.new(
  [],
  comparator: fn (%{revenue: revenue1}, %{revenue: revenue2}) -> compare(revenue1, revenue2) end,
  unique_by: fn (%{id: id}) -> id end
)
```

For `union` and friends, I think we should use the first set given. We can add documentation and tests to show what happens if the order is reversed, but I agree that if the programmer supplies members that don't comply with the comparator then that is their own fault.

For binary representation, I'm not concerned about the `'2'` representation but that two sets with different members (`[50]`, `[{50, 40}]`) have the same representation. They should show their _members_ in the inspect output, not just the keys.

**Comment by siscia** [comment]
That sound good :)

Assuming that your RedBlackTree will take a `:comparator` I am implementing the SortedSet

**Comment by tyre** [comment]
I messed up.

For the RedBlackTree, the comparator operates on the `key`, meaning that any information we want to be compared must be in the `key`. `unique_by` doesn't make sense then because it cannot hold less information that required in the `comparator`.

For example, the above will now have to be

``` elixir

def compare(left, right) do
  cond do
    left < right -> -1
    left === right -> 0
    left > right -> 1
  end
end

SortedSet.new([], comparator: fn (value1, value2) ->

  # If the ids are the same, they are the same
  if value1.id === value2.id do
    0
  else
    case compare(value1.revenue, value2.revenue) do
      # If the revenues are the same but the ids are different, fall back to id comparison for ordering
      0 -> compare(value1.id, value2.id)
      # otherwise return the comparison
      revenue_comparison -> revenue_comparison
    end
  end
end)
```

In that case, we only need a comparator function, since it will compare two keys but store the entire thing.

**Comment by siscia** [comment]
The comparator need to be know by the Tree.

So the only work that need to be done is the one modifying the tree, I am right ?

**Comment by tyre** [comment]
@siscia yes. I've just added the functionality (referenced above) and am doing a quick code review before pushing a new version of [RedBlackTree](https://github.com/senecasystems/red_black_tree).

**Comment by tyre** [comment]
Alright this has been merged in. You can now pass in a custom `:comparator` option that will delegate to the underlying Red-Black tree.

Great idea! Thanks for opening up a PR and helping me understand your needs :smile:

**Comment by siscia** [comment]
You are extremely welcome, thank for your time.

Thanks for your time and effort :)

**Pull request closed without merging**
